#include "test_harness.h"
#include "plugins/cbm-loader/main/d64_parser.h"
#include "plugins/cbm-loader/main/t64_parser.h"
#include "plugins/cbm-loader/main/g64_parser.h"
#include "plugins/cbm-loader/main/cbm_disk_image.h"
#include "plugins/devices/virtual_iec/main/virtual_iec.h"
#include <vector>
#include <cstring>
#include <iostream>
#include <iomanip>
#include <fstream>
#include <filesystem>
#include <algorithm>

namespace fs = std::filesystem;

// Validate BASIC directory listing format generated by disk emulation
// Expected format (used by Commodore disk drives):
// - Load address: 0x01 0x08 (= $0801)
// - BASIC program lines with link pointers
// - Header: line 0 with disk name in quotes
// - File entries: one line per file with blocks, filename, type
// - Footer: "BLOCKS FREE." line
// - Terminator: 0x00 0x00

class BasicDirectoryValidator {
public:
    struct ValidationResult {
        bool isValid = false;
        std::string error;
        uint16_t loadAddr = 0;
        int lineCount = 0;
        std::string diskName;
        std::vector<std::string> files;
        int fileCount = 0;
    };

    static ValidationResult validate(const std::vector<uint8_t>& data) {
        ValidationResult res;
        if (data.size() < 6) {
            res.error = "Data too small";
            return res;
        }

        // Check load address (should be 0x01 0x08 = $0801)
        if (data[0] != 0x01 || data[1] != 0x08) {
            res.error = "Invalid load address";
            return res;
        }
        res.loadAddr = 0x0801;

        // Parse BASIC program lines
        size_t pos = 2; // Start after load address
        while (pos + 2 < data.size()) {
            // Each line: link-lo, link-hi, line-num-lo, line-num-hi, ...data..., 0x00
            uint16_t link = data[pos] | (data[pos+1] << 8);
            pos += 2;

            if (link == 0) {
                // End of program
                res.isValid = true;
                return res;
            }

            // link should point to a valid location
            if (link < 0x0801) {
                res.error = "Invalid link pointer";
                return res;
            }

            // Line number
            if (pos + 2 >= data.size()) {
                res.error = "Unexpected end while reading line number";
                return res;
            }
            uint16_t lineNum = data[pos] | (data[pos+1] << 8);
            pos += 2;

            // Parse line content until 0x00
            std::string lineContent;
            while (pos < data.size() && data[pos] != 0x00) {
                lineContent += (char)data[pos];
                pos++;
            }

            if (pos >= data.size()) {
                res.error = "Line not terminated with 0x00";
                return res;
            }
            pos++; // Skip terminator

            // Classify line
            if (res.lineCount == 0 && lineContent.find("\"") != std::string::npos) {
                // Header line - extract disk name
                size_t start = lineContent.find("\"") + 1;
                size_t end = lineContent.find("\"", start);
                if (end != std::string::npos) {
                    res.diskName = lineContent.substr(start, end - start);
                }
            } else if (lineContent.find("BLOCKS FREE") != std::string::npos) {
                // Footer line
            } else if (lineContent.find("\"") != std::string::npos) {
                // File entry - extract filename
                size_t start = lineContent.find("\"") + 1;
                size_t end = lineContent.find("\"", start);
                if (end != std::string::npos) {
                    std::string filename = lineContent.substr(start, end - start);
                    // Trim trailing spaces from filename
                    while (!filename.empty() && filename.back() == ' ') {
                        filename.pop_back();
                    }
                    res.files.push_back(filename);
                    res.fileCount++;
                }
            }

            res.lineCount++;
        }

        res.isValid = true;
        return res;
    }
};

// Helper to create a test D64 disk image with files
void createTestD64(const std::string& path) {
    std::ofstream file(path, std::ios::binary);
    std::vector<uint8_t> data(174848, 0); // 35 tracks for 1541

    // Track 18, Sector 0: BAM (Block Availability Map)
    uint32_t bamOff = (17 * 21) * 256;
    data[bamOff] = 18;      // Track
    data[bamOff + 1] = 1;   // Sector

    // Track 18, Sector 1: Directory
    uint32_t dirOff = (17 * 21 + 1) * 256;
    data[dirOff] = 0;       // End of chain
    data[dirOff + 1] = 0xFF;

    // Directory entry 0: TESTPROG
    data[dirOff + 2] = 0x82; // PRG file type
    data[dirOff + 3] = 1;    // Track
    data[dirOff + 4] = 0;    // Sector
    std::memcpy(&data[dirOff + 5], "TESTPROG", 8);
    for (int i = 13; i < 21; ++i) data[dirOff + i] = 0xA0;
    data[dirOff + 30] = 42;  // 42 blocks
    data[dirOff + 31] = 0;

    // Directory entry 1: DATAFILE
    uint32_t entry1 = dirOff + 32;
    data[entry1 + 0] = 0x82; // PRG file type
    data[entry1 + 1] = 2;    // Track
    data[entry1 + 2] = 0;    // Sector
    std::memcpy(&data[entry1 + 3], "DATAFILE", 8);
    for (int i = 13; i < 21; ++i) data[entry1 + i] = 0xA0;
    data[entry1 + 30] = 10;  // 10 blocks
    data[entry1 + 31] = 0;

    file.write((char*)data.data(), data.size());
}

TEST_CASE(d64_directory_parsing) {
    // Test that D64 parser correctly reads directory from demo disk
    std::string path = "tests/resources/1541-demo.d64";
    if (!fs::exists(path)) {
        std::cout << "Skipping d64_directory_parsing: demo disk not found\n";
        return;
    }

    D64Parser parser;
    ASSERT(parser.open(path));

    auto dir = parser.getDirectory();
    ASSERT(dir.size() >= 2);

    std::cout << "D64 directory parsed correctly:\n";
    for (const auto& e : dir) {
        std::cout << "  " << e.filename << " (" << e.sizeBlocks << " blocks)\n";
    }
}

TEST_CASE(d64_directory_listing_basic_format) {
    // Test BASIC directory listing validation
    // Verify parser can read files and generate listing data
    std::string path = "tests/resources/1541-demo.d64";
    if (!fs::exists(path)) {
        std::cout << "Skipping d64_directory_listing_basic_format: demo disk not found\n";
        return;
    }

    // Parse the disk
    D64Parser parser;
    ASSERT(parser.open(path));

    auto dirEntries = parser.getDirectory();
    ASSERT(dirEntries.size() >= 1);

    // Verify directory entries have expected structure
    for (const auto& e : dirEntries) {
        ASSERT(!e.filename.empty());
        ASSERT(e.sizeBlocks > 0);
    }
}

TEST_CASE(directory_listing_format_validation) {
    // Test BASIC format validator loads address correctly
    std::vector<uint8_t> listing;
    listing.push_back(0x01); // Load address lo
    listing.push_back(0x08); // Load address hi
    listing.push_back(0x00); // Line link lo
    listing.push_back(0x00); // Line link hi = 0 (end)
    listing.push_back(0x00); // Line number lo
    listing.push_back(0x00); // Line number hi

    auto result = BasicDirectoryValidator::validate(listing);
    ASSERT(result.loadAddr == 0x0801);
}

TEST_CASE(d64_file_reading) {
    // Test that D64 parser can read files from disk
    std::string path = "tests/resources/1541-demo.d64";
    if (!fs::exists(path)) {
        std::cout << "Skipping d64_file_reading: demo disk not found\n";
        return;
    }

    D64Parser parser;
    ASSERT(parser.open(path));

    auto dir = parser.getDirectory();
    for (const auto& entry : dir) {
        std::vector<uint8_t> fileData;
        // Test that files can be read
        parser.readFile(entry.filename, fileData);
    }
}

TEST_CASE(d64_virtual_iec_integration) {
    // Test VirtualIECBus with a D64 disk
    std::string path = "tests/resources/1541-demo.d64";
    if (!fs::exists(path)) {
        std::cout << "Skipping d64_virtual_iec_integration: demo disk not found\n";
        return;
    }

    VirtualIECBus bus(8);
    ASSERT(bus.mountDisk(8, path));

    // Verify disk is mounted
    std::string mountedPath = bus.getMountedDiskPath(8);
    ASSERT(!mountedPath.empty());
}
